INSERT INTO BOOKS (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (1,'TESTAUTHOR1', 'TESTISBN1', '2001-12-15', 'TESTKITAP1');
INSERT INTO BOOKS (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (2,'TESTAUTHOR2', 'TESTISBN2', '2001-12-15', 'TESTKITAP2');
INSERT INTO BOOKS (ID, AUTHOR, ISBN, PUBLISH_DATE, TITLE) VALUES (3,'TESTAUTHOR3', 'TESTISBN3', '2001-12-15', 'TESTKITAP3');